twig:
    default_path: '%kernel.project_dir%/templates'
    # Note: autoescape is enabled by default in Symfony (cannot be configured here)

when@prod:
    twig:
        # Strict variables in production helps catch errors early
        strict_variables: true

when@test:
    twig:
        strict_variables: true
