# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.demo_mode: '%env(bool:APP_DEMO_MODE)%'
    vapid.subject: '%env(VAPID_SUBJECT)%'
    vapid.public_key: '%env(VAPID_PUBLIC_KEY)%'
    vapid.private_key: '%env(VAPID_PRIVATE_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Service\PdfGeneratorService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\ImageOptimizerService:
        arguments:
            $uploadDir: '%kernel.project_dir%/public/uploads'
            $quality: 85
            $generateWebP: true
            $generateAVIF: false

    App\Service\ImageVariantGenerator:
        arguments:
            $publicDir: '%kernel.project_dir%/public'

    App\Command\OptimizeLogoCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Command\GenerateFaviconsCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Command\OptimizeProjectImagesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\Admin\ProjectCrudController:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\EventSubscriber\SecurityHeadersSubscriber:
        arguments:
            $environment: '%kernel.environment%'

    App\EventSubscriber\SecurityLogSubscriber:
        arguments:
            $environment: '%kernel.environment%'

    App\Service\ImageResizerService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Twig\ResponsiveImageExtension:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\WebPushService:
        arguments:
            $vapidSubject: '%vapid.subject%'
            $vapidPublicKey: '%vapid.public_key%'
            $vapidPrivateKey: '%vapid.private_key%'

    App\Service\GoogleOAuthService:
        arguments:
            $googleClientId: '%env(GOOGLE_CLIENT_ID)%'
            $googleClientSecret: '%env(GOOGLE_CLIENT_SECRET)%'

    App\Service\GoogleSearchConsoleService:
        arguments:
            $googleSiteUrl: '%env(GOOGLE_SITE_URL)%'

    App\Service\BingDataImportService:
        arguments:
            $googleSiteUrl: '%env(GOOGLE_SITE_URL)%'

    App\Service\GooglePlacesService:
        arguments:
            $googlePlacesApiKey: '%env(GOOGLE_PLACES_API_KEY)%'
            $googlePlaceId: '%env(GOOGLE_PLACE_ID)%'

    App\Service\LocalPageService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Command\ImportCitiesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Command\SeoExportCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
